### PR TITLE
Fix wrong default druid url and broken getInnerMostQuery

### LINKED ISSUE #527: Bug - Not able to get the nested innermost query
Introduced with this change https://github.com/yahoo/fili/pull/485/files#diff-02ff0b920e378c6f5462c11968ce6333L65

### PR DESCRIPTION
**Pull request by garyluoex**
Resolves #527

### CODE REVIEW

File: fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java [hunk 1]
```diff
@@ -64,7 +64,7 @@
      */
     @JsonIgnore
     default DruidQuery<?> getInnermostQuery() {
-        return getInnerQuery().map(DruidQuery.class::cast).orElse(this);
+        return getInnerQuery().isPresent() ? getInnerQuery().get().getInnermostQuery() : this;
```
Comment (archolewa) [inline fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java]: Why not just do

```java
   return getInnerQuery.map(DruidQuery::getInnermostQuery).orElse(this);
```

File: fili-core/src/main/resources/moduleConfig.properties [hunk 2]
```diff
@@ -86,8 +86,8 @@ bard__max_results_without_filters = 10000
 bard__default_per_page = 10000
 
 # URLs for druid nodes
-bard__druid_broker = [SET ME IN APPLICATION CONFIG]
-bard__druid_coord = [SET ME IN APPLICATION CONFIG]
+# bard__druid_broker = [SET ME IN APPLICATION CONFIG]
+# bard__druid_coord = [SET ME IN APPLICATION CONFIG]
```
Comment (archolewa) [inline fili-core/src/main/resources/moduleConfig.properties]: I don't think we should be commenting these out. The entire purpose of having them be uncommented is that if the customer forgets to set this, the error message will tell them that the setting for this is invalid, and when the error message prints the provided setting, they'll get a hint as to where to put the proper setting.

File: fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java (hunk 1 above)
Comment (garyluoex) [reply fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java]: Null pointer exception if getInnerQuery returns null right?

File: fili-core/src/main/resources/moduleConfig.properties (hunk 2 above)
Comment (garyluoex) [reply fili-core/src/main/resources/moduleConfig.properties]: Then why do we even bother to be backward compatible then? This default will always be chosen over the deprecated ui and non ui settings.

File: fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java (hunk 1 above)
Comment (garyluoex) [reply fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java]: Ok you are right

File: fili-core/src/main/resources/moduleConfig.properties (hunk 2 above)
Comment (michael-mclawhorn) [reply fili-core/src/main/resources/moduleConfig.properties]: @archolewa  To clarify, these being set was breaking this because we were using their UNSETness to indicate backwards compatibility.  Instead they were showing as set, and blowing up unmigrated isntances.

File: fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java (hunk 1 above)
Comment (garyluoex) [reply fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java]: I'm getting a type conflict using this map method, might as well keep it what it is right now since both are basically equivalent.

File: CHANGELOG.md [hunk 3]
```diff
@@ -45,6 +45,9 @@ Current
 
 ### Changed:
 
+- [Fix wrong default druid url and broken getInnerMostQuery](https://github.com/yahoo/fili/pull/528)
+    * Comment out the wrong default druid broker url in module config, add check for validate url in `DruidClientConfigHelper `
```
Comment (michael-mclawhorn) [inline CHANGELOG.md]: Add a few more words to explain that having the default specified was causing the app to fail to do backwards compatibility.

File: fili-core/src/main/resources/moduleConfig.properties (hunk 2 above)
Comment (archolewa) [reply fili-core/src/main/resources/moduleConfig.properties]: @michael-mclawhorn Ah ok that makes sense, I forgot about that.

File: fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java (hunk 1 above)
Comment (archolewa) [reply fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidQuery.java]: Apparently, IntelliJ is stumbling over the template types that neither Maven nor Eclim care about.

Stupid IntelliJ/complicated use of types that confuse our tools or something.
